### ISSUE TITLE
Siridb fails when inserting both floats and ints in same series

### ISSUE THREAD

**Issue by AlmiS** [transceptor-technology/siridb-server#59] opened 2017-03-07 13:02 UTC
Tested on Ubuntu 16.04 amd64
Steps to reproduce error:

1) Install release deb packages:
- siridb-http_1.0.3_amd64.deb
- siridb-manage_2.0.1_amd64.deb
- siridb-prompt_2.0.3_amd64.deb
- siridb-server_2.0.14_amd64.deb

2) Start the server and create new database with siridb-manage
- Time precision = s
- Number (float and integer) sharding duration = 1h
- Log (string) sharding duration = 1d
- Buffer size 1024

3) Start the http interface and insert the following values
```
{
	"series-001": [
		[1488889532, 100],
		[1488889542, 101]
	]
}
```
Making a query at this stage will return the correct values as inserted. As long as we keep inserting integer values or floats ending with .0 (eg. 10.0 or 12.0) everything is fine. However something goes wrong after below insertion:
```
{
	"series-001": [
		[1488889552, 100.12]
	]
}
```
Making a query at this stage will return a wrong value for the last insertion, as seen below:

`{"series-001": [[1488889532, 100], [1488889542, 101], [1488889552, 4636745735603937608]]}`

Going the other way and starting with floats also fails, when an integer is eventually inserted or a float ending with .0.  For instance:
```
{
	"series-002": [
		[1488889667, 234.34],
		[1488889677, 23.23456],
		[1488889687, 34.134]
	]
}

{
	"series-002": [
		[1488889767, 2123.0]
	]
}
```
Doing a query now will return a wrong value for the last insertion, as seen below:
```
{"series-002": [[1488889667, 234.34], [1488889677, 23.23456], [1488889687, 34.134], [1488889767, 1.049e-320]]}
```

Seems like inserting floats after integer values results in a very large number when reading it back out, and inserting integers after floats results in a very small number close to 0.

**Comment by joente** [comment] 2017-03-07 14:06
This behavior is as designed. SiriDB creates a series with a specific type (int of float) based on the first value it receives for a series. All other values are written as this type.

The query `list series name, type` can be used to view the type for existing series. Or in case you want to view just one series: `list series name, type 'my-series'`.  

Maybe somewhere in the future we can change the behavior slightly and skip or cast values of the 'wrong' kind.

**Comment by Thrasd** [comment] 2017-03-07 14:43
The fact that we can not combine `int` and `float` makes sense. 
However, there are still a problem in regards to inserting `float` values. 

If we first insert the following data
```
{
	"series-002": [
		[1488889667, 234.34],
		[1488889677, 23.23456],
		[1488889687, 34.134]
	]
}
```
And then add a `float` value ending in `.0`, like this
```
{
	"series-002": [
		[1488889767, 2123.0]
	]
}
```
It will insert an incorrect value (Like mentioned in the original issue).

When querying the data it looks like this
```
{
	"series-002": [
		[1488889667, 234.34], 
		[1488889677, 23.23456], 
		[1488889687, 34.134], 
		[1488889767, 1.049e-320]]
}
```
So somehow it does not add the `2123.0` value correct, as it instead turns it in to a really small number  `1.049e-320`.

**Comment by joente** [comment] 2017-03-07 15:17
It works with my test database...

"series-002"
timestamp            ┃ value   
━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━
2017-03-07 12:27:47Z │ 234.34  
2017-03-07 12:27:57Z │ 23.23456
2017-03-07 12:28:07Z │ 34.134  
2017-03-07 12:29:27Z │ 2123.0  

How did you insert the data? Did you maybe use JavaScript to insert your data? JavaScript has only support for float values and does not support integer values. Serializing libraries therefore cannot make any difference between integer and float values so they usually write float values like 5.0 as 5 etc.

**Comment by joente** [comment] 2017-03-07 19:27
https://github.com/transceptor-technology/qpack-js has been updated and a function `qpack.double(f)` is added which can be used to force packing a float value. For example you can use qpack to serialize data and force float values like:
```javascript
qpack.encode({
    'series-002': [
        [1488889767, qpack.double(2123.0)]
    ]
}, true);

**Comment by joente** [comment] 2017-03-07 20:05
We have a [siridb-http](https://github.com/transceptor-technology/siridb-http) connector with a webpage from where it is possible to insert json data. This website actually had the same issue with JavaScript and float/integer values. This issue is now fixed and the fix will be included in the next version. 

see: https://github.com/transceptor-technology/siridb-http/issues/7

**Comment by AlmiS** [comment] 2017-03-07 20:12
Yes I was using siridb-http through the website it provides to insert the data. The JavaScript issue must be what caused the problem then. I will test tomorrow with the latest code from siridb-http to confirm the issue is fixed.

**Comment by joente** [comment] 2017-03-07 20:21
I've build a new version (including deb package) for siridb-http which can be downloaded here: https://github.com/transceptor-technology/siridb-http/releases/tag/1.0.4

**Comment by AlmiS** [comment] 2017-03-08 10:00
Yes, it seems this has fixed the issue of inserting floats from the website on siridb-http.

However, there is another issue when reading floats from SiriDB on 32bit cpus. Using python 3.5.2 with the newest siridb-connector and qpack installed through PIP, I receive a 'Bus Error' when executing the below python code on a 32bit rpi with debian jessie.

```
import asyncio
from siridb.connector import SiriDBClient

async def example(siri):
    # Start connecting to SiriDB.
    # .connect() returns a list of all connections referring to the supplied
    # hostlist. The list can contain exceptions in case a connection could not
    # be made.    
    await siri.connect()

    try:
        resp = await siri.query("select * from 'series-301'")
        print(resp)
    finally:
        # Close all SiriDB connections.
        siri.close()


siri = SiriDBClient(
    username='iris',
    password='siri',
    dbname='brume',
    hostlist=[('localhost', 14000)],  # Multiple connections are supported
    keepalive=True)

loop = asyncio.get_event_loop()
loop.run_until_complete(example(siri))
```
Running the same code from my 64bit Ubuntu 16.04 laptop (changing only the hostlist to point to the same sirdb-server on the rpi) works fine and returns the data: 

`{"series-301": [[1488963879, 14.5], [1488963927, 5.88]]}`

It does not seem to matter whatever the actual siridb-server is running on a 32bit or a 64bit, the issue is related to reading the values back from the database with the connector on 32bit machines. This only happens when the series consists of floats and there is more than 1 float value in the serie. Series with integers are returned fine.

Maybe this is a seperate issue which sould be put under the siridb-connector project?

**Comment by joente** [comment] 2017-03-08 10:55
Strange.. I did the test on a 32bit kernel using Python 3.5.2 but I did not ran into this issue.

My exact code:
```python
import asyncio
from siridb.connector import SiriDBClient

async def test():
    siri = SiriDBClient('iris', 'siri', 'dbtest', [('localhost', 9000)])
    await siri.connect()
    try:
        await siri.insert({"series-301": [[1488963879, 14.5], [1488963927, 5.88]]})
        res = await siri.query('select * from "series-301"')
        print(res)
    finally:
        siri.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())
```

The output returned: `{'series-301': [[1488963879, 14.5], [1488963927, 5.88]]}`

The fact that you get a `Bus error` might indicate a problem with the c-module for qpack. 
Can you check if you have the latest version installed?

`pip3 freeze | grep qpack`

The latest version is `qpack==0.0.13`

QPack has Python fallback code in case the c-module is not able to compile. You can force using the fallback by using this code on top of your script:
```python
import qpack
from qpack.fallback import packb, unpackb
qpack.packb = packb
qpack.unpackb = unpackb
# ... rest of the code, data will now be packed and unpacked using python code instead of the c-module
```

If the error still exists we at least know it is not the c-module for qpack.

**Comment by AlmiS** [comment] 2017-03-08 11:37
I'm running python 3.5.2 and pip freeze shows ´qpack==0.0.13´.
Using the fallback method works. Maybe the issue is related to the arm architecture of the Raspberry PI.

**Comment by joente** [comment] 2017-03-08 15:05
I have updated qpack to version 0.0.14 which fixed some size checking but i'm not sure it has anything to do with the error you received. On the master branch for qpack a unittest is added. @AlmiS , is it possible for you to run this test? (https://github.com/transceptor-technology/qpack/tree/master/test)

**Comment by AlmiS** [comment] 2017-03-08 15:20
Ok, I upgraded both the Raspberry PI and my laptop to qpack version 0.0.14. Python version for both is 3.5.2.
Running the test on my laptop yields the output:
```
....
----------------------------------------------------------------------
Ran 4 tests in 0.002s

OK
```
Running on the Raspberry PI gives

`...Bus error`

**Comment by joente** [comment] 2017-03-08 15:57
@AlmiS : we found this article on the Internet which explains possible float errors on a rpi: https://www.raspberrypi.org/forums/viewtopic.php?t=102400&p=708988

I have changed some code which should solve the above issue. Can you update once more (version 0.0.15) and run the test again?

**Comment by joente** [comment] 2017-03-08 16:17
Closing this issue and continue on https://github.com/transceptor-technology/qpack/issues/1 since the cause of the problem is the qpack library.

**Closed by joente** 2017-03-08 16:17 UTC
